# Generated by Django 5.1.1 on 2024-09-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ews_list", "0002_alter_ewsitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ewsitem",
            name="sender",
            field=models.EmailField(max_length=254),
        ),
    ]
