"""
Django settings for todo_manager project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$tr33n=7s+f#esfs41dazv0w5#z0ss1teh7rqom)2&p^(rga3l"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "todo_list.apps.TodoListConfig",  # приложение со списком дел
    "ews_list.apps.EWSListConfig",  # приложение для работы с почтой
    "pwp_list.apps.PWPListConfig",  # приложение для работы с БД
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "todo_manager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "todo_manager.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",  # BASE_DIR -> todo_manager
    }
}

# For MySQL connection
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#           "HOST": "flet4er.2bp.ru",
#           "NAME": "имя базы данных",
#       "PASSWORD": "пароль",
#           "PORT": "порт бд",
#           "USER": "имя пользователя",
#        "OPTIONS": {
#             "read_default_file": "./my.cnf",
#         },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

load_dotenv('../.env')
userid = os.environ.get('USERID')
dbpass = os.environ.get('SECRET_KEY')
db_url = os.environ.get('DATABASE_URL')
dbname = os.environ.get('DATABASENAME')
dbhost = os.environ.get('DBHOST')
dbport = os.environ.get('DBPORT')
dbliten = os.environ.get('DBSQLITENAME')
dblitepsw = os.environ.get('DBSQLITEPSW')
percentile = os.environ.get('PERCENTILE')
exch_username = os.environ.get('EXCH_USERID')
exch_userkey = os.environ.get('EXCH_USERKEY')
exch_serverurl = os.environ.get('EXCH_SERVER_URL')
exch_usersmtpaddr = os.environ.get('EXCH_SMTP_USERADDR')
exch_authtype = os.environ.get('EXCH_AUTH_TYPE')
inb_fold = os.environ.get('INBOX_FOLDER')
inb_fold_sales = os.environ.get('INBOX_FOLDER_SALES')
inb_fold_supp = os.environ.get('INBOX_FOLDER_SUPP')
inb_fold_other = os.environ.get('INBOX_FOLDER_OTHER')
email_templ_path = os.environ.get('EMAIL_TEMPL_PATH')
draft_email_templ_path = os.environ.get('DRAFT_EMAIL_TEMPL')
tmp_path = os.environ.get('TMP_PATH')
email_templ_path_mac = os.environ.get('EMAIL_TEMPL_PATHMAC')
